models.py
from app import db
from datetime import datetime
import re


from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r"[^\w+]"
    return re.sub(pattern, "-", str(s))


ad_rubrics = db.Table(
    "ad_rubrics",
    db.Column("ad_id", db.Integer, db.ForeignKey("ad.id")),
    db.Column("rubric_id", db.Integer, db.ForeignKey("rubric.id")),
)


class Ad(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now)

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    rubrics = db.relationship(
        "Rubric", secondary=ad_rubrics, backref=db.backref("ads"), lazy="dynamic"
    )

    def __init__(self, *args, **kwargs):
        super(Ad, self).__init__(*args, **kwargs)
        self.generate_slug()

    def __repr__(self):
        return f"<Ad id: {self.id}, title: {self.title}>"


class Rubric(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Rubric, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.name:
            self.slug = slugify(self.name)

    def __repr__(self):
        return f"{self.name}"


roles_users = db.Table(
    "roles_users",
    db.Column("user_id", db.Integer(), db.ForeignKey("user.id")),
    db.Column("role_id", db.Integer(), db.ForeignKey("role.id")),
)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

ads/forms.py
from wtforms import Form, StringField, TextAreaField


class AdForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

ads/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Ad, Rubric
from .forms import AdForm
from app import db

from flask import request
from flask import redirect
from flask import url_for


from flask_security import login_required


ads = Blueprint("ads", __name__, template_folder="templates")


@ads.route('/create', methods=['POST', 'GET'])
@login_required
def create_ad():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            ad = Ad(title=title, body=body)
            db.session.add(ad)
            db.session.commit()
        except:
            print("Unsuccessfully")

        return redirect(url_for('ads.index'))

    form = AdForm()
    return render_template('ads/create_ad.html', form=form)


@ads.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_ad(slug):
    ad = Ad.query.filter(Ad.slug == slug).first_or_404()
    if request.method == "POST":
        ad.title = request.form['title']
        ad.body = request.form['body']
        db.session.commit()
        return redirect(url_for('ads.ad_detail', slug=ad.slug))

    form = AdForm(obj=ad)
    return render_template('ads/edit_ad.html', ad=ad, form=form)


@ads.route("/")
def index():
    q = request.args.get('q')

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        adv = Ad.query.filter(Ad.title.contains(q) | Ad.body.contains(q))
    else:
        adv = Ad.query.order_by(Ad.created.desc())
    pages = adv.paginate(page=page, per_page=5)

    return render_template("ads/index.html", pages=pages)


@ads.route("/<slug>")
def ad_detail(slug):
    ad = Ad.query.filter(Ad.slug == slug).first_or_404()
    rubrics = ad.rubrics
    return render_template("ads/ad_detail.html", ad=ad, rubrics=rubrics)


@ads.route("/rubric/<slug>")
def rubric_detail(slug):
    rubric = Rubric.query.filter(Rubric.slug == slug).first_or_404()
    adv = rubric.ads
    return render_template("ads/rubric_detail.html", rubric=rubric, ads=adv)

app.py
from flask import Flask
from flask import redirect, url_for, request
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_security import Security
from flask_security import current_user

from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_admin import AdminIndexView

from flask_security import SQLAlchemyUserDatastore


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command("db", MigrateCommand)


from models import *


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role("admin")

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for("security.login", next=request.url))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)


class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class AdAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'rubrics']


class RubricAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'ads']


admin = Admin(app, "B_board", url="/", index_view=HomeAdminView(name="Home"))
admin.add_view(AdAdminView(Ad, db.session))
admin.add_view(RubricAdminView(Rubric, db.session))

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db

from ads.blueprint import ads

import view

app.register_blueprint(ads, url_prefix="/board")

if __name__ == "__main__":
    app.run()

ads/templates/ads/ad_detail.html
{% extends "base.html"%}
{% block title %}
{{ ad.title }}
{% endblock %}

{% block content_title %}
    {{ ad.title }}
{% endblock %}



{% block content %}
    <div class = 'rubrics'>
        {% for r in rubrics %}
         <a href = "{{ url_for('ads.rubric_detail', slug=r.slug)}}">
             <span class="badge badge-info">{{ r.name }}</span>
         </a>
        {% endfor %}
    </div>
    <div class = 'main-content'>
        {{ ad.body }}
    </div>
{% endblock %}

ads/templates/ads/create_ad.html
{% extends "base.html" %}
{% block title %}
Create new ad
{% endblock %}

{% block content_title %}
Create new ad
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('ads.create_ad')}}", method ='POST'>

            {% for field in form %}
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info">Create</button>
        </form>
    </div>
{% endblock %}

ads/templates/ads/edit_ad.html
{% extends "base.html" %}
{% block title %}
Edit ad
{% endblock %}

{% block content_title %}
Edit new ad
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('ads.edit_ad', slug=ad.slug)}}", method ='POST'>

            {% for field in form %}
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info">Save</button>
        </form>
    </div>
{% endblock %}

ads/templates/ads/index.html
{% extends "base.html"%}
{% block title %}
List of ads
{% endblock %}

{% block content_title %}
List of ads
{% endblock %}

{% block content %}
    {% for ad in pages.items %}
    <p>
       <a href="{{ url_for('ads.ad_detail', slug=ad.slug) }}"> {{ ad.title }}</a>
    </p>
    {% endfor %}
<nav>
  <ul class="pagination">
    <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}}>
      <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>

      {% for page in pages.iter_pages() %}

      <li {% if  page == pages.page %} class="page-item active" {% endif %}} aria-current="page">
      <a class="page-link" href="./?page={{ page}}">{{ page }}<span class="sr-only">(current)</span></a>

      {% endfor %}

    <li {% if not pages.has_next %} class="page-item disabled" {% endif %}}>
      <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
    </li>
  </ul>
</nav>
{% endblock %}

ads/templates/ads/rubric_detail.html
{% extends "base.html"%}
{% block title %}
{{ rubric.name }} advertisements
{% endblock %}

{% block content_title %}
    Advertisements for "{{ rubric.name }}" rubric:
{% endblock %}

{% block content %}
    {% for ad in ads %}
        <div class = 'ad'>
            <a href="{{ url_for('ads.ad_detail', slug=ad.slug)}}">{{ ad.title }}</a>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %} | Bulletin Board
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-ligh" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href=" {{url_for('index')}} ">Main</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href=" {{ url_for('ads.index') }} ">List of ads <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          {% if current_user.has_role('admin') %}
          <a class="nav-link" href="/admin">Admin</a>
          {% endif %}
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0" method="GET">

      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">

      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </div>
</nav>
<div class="container">
    <div class="row">
        <h1>
            {% block content_title %}

            {% endblock %}
        </h1>

    </div>
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

templates/create_ad.html
{% extends "base.html"%}
{% block title %}
Create new ad
{% endblock %}

{% block content_title %}
Create new ad
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('ads.create_ad')}}, method ='Post'">

            {% for field in form %}
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info">Create</button>
        </form>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}

    Main

{% endblock %}

{% block content_title %}

    Main

{% endblock %}

{% block content %}

    <div>
        <p>Welcome to our website!</p>
    </div>

{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends "base.html"%}
{% block title %}
Login
{% endblock %}

{% block content_title %}
{{ _('Login') }}
{% endblock %}


{% block content %}
<div class="col-md-6 ">
  {% from "security/_macros.html" import render_field_with_errors, render_field %}
  {% include "security/_messages.html" %}
  <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
    {{ login_user_form.hidden_tag() }}
    {{ render_field_with_errors(login_user_form.email, class='form-control') }}
    {{ render_field_with_errors(login_user_form.password, class='form-control') }}
    {{ render_field_with_errors(login_user_form.remember) }}
    {{ render_field(login_user_form.next) }}
    {{ render_field(login_user_form.submit, class='btn btn-info') }}
  </form>
  {% include "security/_menu.html" %}
</div>
{% endblock %}